on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install cURL
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev zlib1g-dev libssl-dev libffi-dev zlib1g-dev libbz2-dev liblzma-dev build-essential libglpk40 openssh-client curl nano less libxt6 libcurl4-openssl-dev libgsl-dev libpng-dev git python3 python3-pip python3-venv
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "reticulate"))
          reticulate::virtualenv_create("r-reticulate")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: |
          install.packages(c("remotes", "rcmdcheck", "reticulate"))
          reticulate::virtualenv_create("r-reticulate")
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
